version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: dating
    environment:
      POSTGRES_USER: dating
      POSTGRES_PASSWORD: 57ab2bb0
      POSTGRES_DB: dating
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
